blank_issues_enabled: true
contact_links:
  - name: Questions & discussion
    url: https://github.com/Fiskeretta/fiskeretta-diagnostics/discussions
    about: For usage questions and general discussion, please use Discussions.
